### ISSUE TITLE
Links are not transferred when printing PDF doc

### ISSUE THREAD

**Issue by teddywaweru** [flathub/org.onlyoffice.desktopeditors#73]
I'm shifting from a Windows environment, where MS Office would include the links to the PDF upon printing(or exporting). On OnlyOffice, the links are not maintained in PDF prints. There is no option to enable this or not.

For reference I'm using v7.1.1 on Manjaro Arch Linux. The OnlyOffice came pre-installed with the OS.

**Comment by ShockwaveNN** [comment]
Hi, I think this may be a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/189

But this issue is resolved

Could you describe exact steps that you did, in which editor you've opened resulting PDF?
And if by any chance you got non-Arch system nearby, but with out default deb or rpm package of DesktopEditors - and try to reproduce same issue, so we can rule out if this only fltapak-on-Arch problem or for any system

**Comment by teddywaweru** [comment]
I realized my error in this: I had picked to print the doc as PDF, & that lead to a doc without links. But choosing to save the doc results in a PDF with links still embedded. 👍
In Windows, the print-to-PDF results in a doc with links. That's the feature that I was trying to use.

**Comment by ShockwaveNN** [comment]
@teddywaweru Sorry, I didn't get you at all, could you explain step-by-step how to create failuty PDF and maybe share original doc?

**Comment by teddywaweru** [comment]
Sorry, so I wanted to create the PDF. I selected the File->Print Option, & selected PDF as the output. In this case the PDF did not contain any links.

**Comment by ShockwaveNN** [comment]
I need more information from you

Which file you've tried to print and which PDF Viewer you've checked that pdf has no links (and please check any other PDF Viewers if you've checked only one)

**Comment by teddywaweru** [comment]
Maybe I'm not clear in my explanations, so I decided to make a screencast of the flow: 

https://user-images.githubusercontent.com/57697272/185252100-6025a470-d2db-4601-be87-8dcbd40d1a97.mp4

**Comment by ShockwaveNN** [comment]
@teddywaweru Could you check if link is correct for `File -> Save as -> PDF` menu?

Because you've selected the Print menu, it's for printing on a real page, so you cannot click on the link on the real page
And the ability to direct print not to the real page, but to virtual pdf printer is just an option
Ms Office handles `save as pdf` and `print -> as pdf` same way, loosing link in second case

**Comment by teddywaweru** [comment]
Link is okay in Saving As PDF.

**Comment by ShockwaveNN** [comment]
@teddywaweru Glad that problem is resolved :+1:
